In [3]:
import pandas as pd 
from faker import Faker 
import numpy as np 

fake = Faker()
np.random.seed(42)
cities = ['Rome', 'Milan', 'Florence', 'Naples']

n = 100
data = {
    'Name': [f"{fake.first_name()} {fake.last_name()}" for _ in range(n)],
    'Age' : np.random.randint(20, 60, n),
    'City': np.random.choice(cities, n),
    'Score' : np.random.randint(0,101, n)
}

df = pd.DataFrame(data)
df

                Name  Age      City  Score
0        Thomas Hall   58    Naples     43
1       Thomas Smith   48  Florence     23
2      Brenda Rogers   34  Florence     78
3        Andre Weber   27     Milan     58
4      Melanie Marsh   40    Naples     31
..               ...  ...       ...    ...
95      Edward Munoz   28     Milan     18
96     Clayton Yates   27      Rome     47
97          Lori Kim   31      Rome     79
98        Tammy Kidd   53  Florence      2
99  Timothy Williams   52     Milan     19

[100 rows x 4 columns]

In [4]:
grouped = df.groupby('City')
grouped['Score'].mean()

City
Florence    48.468750
Milan       45.619048
Naples      47.047619
Rome        54.538462
Name: Score, dtype: float64

In [5]:
df.groupby('City')['Score'].agg(['mean','max','count'])

               mean  max  count
City
Florence  48.468750  100     32
Milan     45.619048   95     21
Naples    47.047619   91     21
Rome      54.538462   98     26

In [17]:
print(df['Score'].mean())
grouped = df.groupby('City')
print(grouped['Score'].mean())

print(grouped['Name'].count())

print(grouped['Score'].max())

df.groupby('City').agg({
    'Score' : ['mean', 'max', 'count'],
    'Age'   : ['max', 'count']
})

49.15
City
Florence    48.468750
Milan       45.619048
Naples      47.047619
Rome        54.538462
Name: Score, dtype: float64
City
Florence    32
Milan       21
Naples      21
Rome        26
Name: Name, dtype: int64
City
Florence    100
Milan        95
Naples       91
Rome         98
Name: Score, dtype: int64

              Score            Age
               mean  max count max count
City
Florence  48.468750  100    32  55    32
Milan     45.619048   95    21  55    21
Naples    47.047619   91    21  59    21
Rome      54.538462   98    26  59    26