In [9]:
import pandas as pd
import numpy as np 
from faker import Faker 

np.random.seed(42)
fake = Faker()

n = 10 

data = {
    'Name' : [f"{fake.first_name()} {fake.last_name()}" for _ in range(n)],
    'Age'  : np.random.randint(20,60, size=n), 
    'City' : [fake.city() for _ in range(n)],
    'Score' : np.random.randint(0, 101, n)
}

df = pd.DataFrame(data, index=[f"P{i+1}" for i in range(n)])
df

                Name  Age               City  Score
P1       Danny Davis   58          Haleshire     87
P2     Carolyn Mcgee   48       Gilbertville     99
P3      Raymond Rich   34          Amberland     23
P4     Damon Jackson   27        North David      2
P5   Keith Mccormick   40  South Angelashire     21
P6    Melissa Walker   58  Lake Jenniferport     52
P7         Juan Hall   38          Millsland      1
P8       Mary Miller   42   North Kellymouth     87
P9    Pamela Kennedy   30      Williamsville     29
P10  Jeffrey Simpson   30           Hillfort     37

In [10]:
print(df.loc['P3'])
print(df.iloc[2])

df_filtered = df[(df['Age'] >= 30) & (df['Score'] >= 50)].copy()
df_filtered['Passed'] = df_filtered['Score'] >= 60
df_filtered

Name     Raymond Rich
Age                34
City        Amberland
Score              23
Name: P3, dtype: object
Name     Raymond Rich
Age                34
City        Amberland
Score              23
Name: P3, dtype: object

              Name  Age               City  Score  Passed
P1     Danny Davis   58          Haleshire     87    True
P2   Carolyn Mcgee   48       Gilbertville     99    True
P6  Melissa Walker   58  Lake Jenniferport     52   False
P8     Mary Miller   42   North Kellymouth     87    True