In [2]:
import pandas as pd 
from faker import Faker 
import numpy as np 

np.random.seed(42)
Faker.seed(42)

In [10]:
date_range = pd.date_range(start='2025-01-01', end='2025-06-21', freq='D')
random_dates = np.random.choice(date_range, 5)

random_dates = pd.to_datetime(random_dates)
random_dates = pd.Series(np.sort(random_dates))
print(random_dates.dt.normalize())

0   2025-01-13
1   2025-02-19
2   2025-04-09
3   2025-06-01
4   2025-06-02
dtype: datetime64[ns]

In [15]:
import pandas as pd 
 
n = 10
df = pd.DataFrame({
    'Date' : np.random.choice(date_range, n),
    'Value' : np.random.randint(1,101,n)
})

df['Date'] = pd.to_datetime(df['Date'])
df

        Date  Value
0 2025-04-27     34
1 2025-03-03     96
2 2025-01-23     48
3 2025-05-07     89
4 2025-05-17      1
5 2025-05-20     16
6 2025-05-09     61
7 2025-02-27     64
8 2025-05-02     63
9 2025-01-01     69

In [18]:
df['Year'] = df['Date'].dt.year
df['Month'] = df['Date'].dt.month 
df['Day'] = df['Date'].dt.day 
df['Weekday'] = df['Date'].dt.weekday
df

        Date  Value  Year  Month  Day  Weekday
0 2025-04-27     34  2025      4   27        6
1 2025-03-03     96  2025      3    3        0
2 2025-01-23     48  2025      1   23        3
3 2025-05-07     89  2025      5    7        2
4 2025-05-17      1  2025      5   17        5
5 2025-05-20     16  2025      5   20        1
6 2025-05-09     61  2025      5    9        4
7 2025-02-27     64  2025      2   27        3
8 2025-05-02     63  2025      5    2        4
9 2025-01-01     69  2025      1    1        2

In [47]:
import numpy as np
n=50

df = pd.DataFrame({
    'Date': np.random.choice(pd.date_range(start='2023-01-01',end='2024-01-01',freq='M'),n),
    'Value' : np.random.randint(0,101,n)
})
df['Month'] = df['Date'].dt.month 
df.groupby('Month')['Value'].sum().sort_index()

/tmp/ipykernel_8720/2665262541.py:5: FutureWarning: 'M' is deprecated and will be removed in a future version, please use 'ME' instead.
  'Date': np.random.choice(pd.date_range(start='2023-01-01',end='2024-01-01',freq='M'),n),

Month
1     214
2     128
3     197
4     189
5     257
6     300
7     153
8     143
9     209
10    308
11    330
12    212
Name: Value, dtype: int64

In [40]:
date_range = pd.date_range(start='2023-01-01', end='2025-01-01', freq='M')
date_range

/tmp/ipykernel_8720/2001044770.py:1: FutureWarning: 'M' is deprecated and will be removed in a future version, please use 'ME' instead.
  date_range = pd.date_range(start='2023-01-01', end='2025-01-01', freq='M')

DatetimeIndex(['2023-01-31', '2023-02-28', '2023-03-31', '2023-04-30',
               '2023-05-31', '2023-06-30', '2023-07-31', '2023-08-31',
               '2023-09-30', '2023-10-31', '2023-11-30', '2023-12-31',
               '2024-01-31', '2024-02-29', '2024-03-31', '2024-04-30',
               '2024-05-31', '2024-06-30', '2024-07-31', '2024-08-31',
               '2024-09-30', '2024-10-31', '2024-11-30', '2024-12-31'],
              dtype='datetime64[ns]', freq='ME')

In [49]:
df = df.sort_values('Date')
df = df.set_index('Date')
df

            Value  Month
Date
2023-01-31     56      1
2023-01-31     23      1
2023-01-31     93      1
2023-01-31     42      1
2023-02-28     54      2
2023-02-28     72      2
2023-02-28      2      2
2023-03-31    100      3
2023-03-31     97      3
2023-04-30     98      4
2023-04-30     73      4
2023-04-30     18      4
2023-05-31      0      5
2023-05-31     21      5
2023-05-31     58      5
2023-05-31     24      5
2023-05-31     82      5
2023-05-31     61      5
2023-05-31     11      5
2023-06-30     80      6
2023-06-30     25      6
2023-06-30     43      6
2023-06-30     55      6
2023-06-30     97      6
2023-07-31     46      7
2023-07-31     88      7
2023-07-31     19      7
2023-08-31     11      8
2023-08-31     60      8
2023-08-31     72      8
2023-09-30     16      9
2023-09-30     53      9
2023-09-30     68      9
2023-09-30     72      9
2023-10-31     34     10
2023-10-31     98     10
2023-10-31     41     10
2023-10-31     60     10
2023-10-31     43     10
2023-10-31     32     10
2023-11-30     50     11
2023-11-30     65     11
2023-11-30     48     11
2023-11-30     16     11
2023-11-30     54     11
2023-11-30     97     11
2023-12-31    100     12
2023-12-31     38     12
2023-12-31     35     12
2023-12-31     39     12

In [50]:
monthly_sum = df.resample('M')['Value'].sum()
monthly_sum

/tmp/ipykernel_8720/2482712463.py:1: FutureWarning: 'M' is deprecated and will be removed in a future version, please use 'ME' instead.
  monthly_sum = df.resample('M')['Value'].sum()

Date
2023-01-31    214
2023-02-28    128
2023-03-31    197
2023-04-30    189
2023-05-31    257
2023-06-30    300
2023-07-31    153
2023-08-31    143
2023-09-30    209
2023-10-31    308
2023-11-30    330
2023-12-31    212
Freq: ME, Name: Value, dtype: int64

In [ ]:
# complete exercise 
import pandas as pd
import numpy as np

np.random.seed(42)
n = 50

df = pd.DataFrame({
    'Date': np.random.choice(pd.date_range(start='2023-01-01', end='2024-01-01', freq='M'), n),
    'Value': np.random.randint(0, 101, n)
})

df['Date'] = pd.to_datetime(df['Date'])
df = df.sort_values('Date')
df = df.set_index('Date')

# Resample mensile
'''
resample() in pandas funziona quasi come un groupby(),
ma sul tempo
 --> un groupby temporale che permette di aggregare dati
     su una nuova frequenza temporale 
 --> è necessario avere un indice temporale (DatetimeIndex)
il nome "resample" perchè 
 --> prendi una serie temporale e ricampiona (riorganizza) i dati 
     su un'altra frequenza temporale 
     e.g. : se hai dati giornalieri, puoi aggregarli mensilmente,
            settimanalmente, annualmente etc.
 --> in pratica: ristruttura l'asse temporale creando intervalli regolari
     ed applica l'aggregazione scelta entro ogni intervallo
            
    groupby('column')
    resample('M') -> crea tutti i bucket temporali, anche se vuoti
         

'''
monthly_sum = df.resample('M')['Value'].sum()
print("Resample mensile:")
print(monthly_sum)

# Groupby per mese (numerico)
df['Month'] = df.index.month
grouped = df.groupby('Month')['Value'].sum().sort_index()
print("\nGroupby per mese:")
print(grouped)

Resample mensile:
Date
2023-01-31     86
2023-02-28     40
2023-03-31    278
2023-04-30    123
2023-05-31    286
2023-06-30     95
2023-07-31    199
2023-08-31    220
2023-09-30    181
2023-10-31    250
2023-11-30    396
2023-12-31    358
Freq: ME, Name: Value, dtype: int64

Groupby per mese:
Month
1      86
2      40
3     278
4     123
5     286
6      95
7     199
8     220
9     181
10    250
11    396
12    358
Name: Value, dtype: int64

/tmp/ipykernel_8720/514217950.py:9: FutureWarning: 'M' is deprecated and will be removed in a future version, please use 'ME' instead.
  'Date': np.random.choice(pd.date_range(start='2023-01-01', end='2024-01-01', freq='M'), n),
/tmp/ipykernel_8720/514217950.py:18: FutureWarning: 'M' is deprecated and will be removed in a future version, please use 'ME' instead.
  monthly_sum = df.resample('M')['Value'].sum()

In [52]:
import pandas as pd

dates = pd.to_datetime(['2023-01-01', '2023-01-03', '2023-01-10'])
values = [10, 20, 30]

df = pd.DataFrame({'Date': dates, 'Value': values})
df = df.set_index('Date')

result = df.resample('D').sum()
print(result)

            Value
Date
2023-01-01     10
2023-01-02      0
2023-01-03     20
2023-01-04      0
2023-01-05      0
2023-01-06      0
2023-01-07      0
2023-01-08      0
2023-01-09      0
2023-01-10     30