In [1]:
import pandas as pd 
import numpy as np 

url_1 = 'https://raw.githubusercontent.com/guipsamora/pandas_exercises/master/05_Merge/Auto_MPG/cars1.csv'
url_2 = 'https://raw.githubusercontent.com/guipsamora/pandas_exercises/master/05_Merge/Auto_MPG/cars2.csv'

cars1 = pd.read_csv(url_1)
cars2 = pd.read_csv(url_2)

In [3]:
cars1.head(2)

,mpg,cylinders,displacement,horsepower,weight,acceleration,model,origin,car,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13
0,18.0,8,307,130,3504,12.0,70,1,chevrolet chevelle malibu,NaN,NaN,NaN,NaN,NaN
1,15.0,8,350,165,3693,11.5,70,1,buick skylark 320,NaN,NaN,NaN,NaN,NaN

In [4]:
cars2.head(2)

,mpg,cylinders,displacement,horsepower,weight,acceleration,model,origin,car
0,33.0,4,91,53,1795,17.4,76,3,honda civic
1,20.0,6,225,100,3651,17.7,76,1,dodge aspen se

In [11]:
print("Cols in cars1: ")
print(cars1.dtypes)

print("Cols in cars2: ")
print(cars2.dtypes)

Cols in cars1:
mpg             float64
cylinders         int64
displacement      int64
horsepower       object
weight            int64
acceleration    float64
model             int64
origin            int64
car              object
Unnamed: 9      float64
Unnamed: 10     float64
Unnamed: 11     float64
Unnamed: 12     float64
Unnamed: 13     float64
dtype: object
Cols in cars2:
mpg             float64
cylinders         int64
displacement      int64
horsepower       object
weight            int64
acceleration    float64
model             int64
origin            int64
car              object
dtype: object

In [7]:
cars1.dtypes

mpg             float64
cylinders         int64
displacement      int64
horsepower       object
weight            int64
acceleration    float64
model             int64
origin            int64
car              object
Unnamed: 9      float64
Unnamed: 10     float64
Unnamed: 11     float64
Unnamed: 12     float64
Unnamed: 13     float64
dtype: object

It seems our first dataset has some unnamed blank columns, fix cars1

In [13]:
cars1 = cars1.loc[:, :'car'] 
cars1.dtypes

mpg             float64
cylinders         int64
displacement      int64
horsepower       object
weight            int64
acceleration    float64
model             int64
origin            int64
car              object
dtype: object

What is the number of observations in each dataset?

In [14]:
print(f"Observations in cars1: {cars1.shape[0]}")
print(f"Observations in cars2: {cars2.shape[0]}")

Observations in cars1: 198
Observations in cars2: 200

In [22]:
def check_cols(one, two):
    return set(one.columns) == set(two.columns)

print(f"Equal Features Check: {'yes' if check_cols(cars1, cars2) else 'no'}")

Equal Features Check: yes

Join cars1 and cars2 into a single DataFrame called cars

In [24]:
cars = pd.concat([cars1,cars2])
cars.shape[0]

398

In [25]:
cars.head()

,mpg,cylinders,displacement,horsepower,weight,acceleration,model,origin,car
0,18.0,8,307,130,3504,12.0,70,1,chevrolet chevelle malibu
1,15.0,8,350,165,3693,11.5,70,1,buick skylark 320
2,18.0,8,318,150,3436,11.0,70,1,plymouth satellite
3,16.0,8,304,150,3433,12.0,70,1,amc rebel sst
4,17.0,8,302,140,3449,10.5,70,1,ford torino

There is a column missing, called owners. Create a random number Series from 15,000 to 73,000.

In [26]:
np.random.seed(42)

In [27]:
cars['owner'] = np.random.randint(15000, 73001, cars.shape[0])
cars.tail()

,mpg,cylinders,displacement,horsepower,weight,acceleration,model,origin,car,owner
195,27.0,4,140,86,2790,15.6,82,1,ford mustang gl,62333
196,44.0,4,97,52,2130,24.6,82,2,vw pickup,18436
197,32.0,4,135,84,2295,11.6,82,1,dodge rampage,23754
198,28.0,4,120,79,2625,18.6,82,1,ford ranger,25677
199,31.0,4,119,82,2720,19.4,82,1,chevy s-10,20895